# Single quotes being faster is hardly measurable and only affects parse time.
# # Enforcing double quotes reduces the times where you need to change them
# # when introducing an interpolation. Use single quotes only if their semantics
# # are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# rubocop default rules want the gems in alphabetical order
#   this disables that
Bundler/OrderedGems:
  Enabled: false

#80 is just too small
Metrics/LineLength:
  Max: 100

Style/RedundantReturn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 15