FROM centos:centos7 as base

ENV DEV_PACKAGES tar which

RUN yum -y install $DEV_PACKAGES; yum clean all

##################################################################

FROM base as ssh

RUN yum -y update; yum clean all
RUN yum -y install openssh-server passwd

RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''

ENTRYPOINT ["/usr/sbin/sshd", "-D"]

